/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programaFTLC;

import java.awt.Color;
import java.io.IOException;
import javax.swing.JRootPane;

/**
 *
 * @author paco_
 */
public class ventanaPrcp extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrcp
     */
    int x,y;
    public ventanaPrcp() {
        initComponents();
      this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pa = new javax.swing.JPanel();
        button3 = new boton.button();
        button2 = new boton.button();
        jPanel1 = new javax.swing.JPanel();
        btncalc = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        lbltxt = new javax.swing.JLabel();
        btn5 = new javax.swing.JPanel();
        lbltxt9 = new javax.swing.JLabel();
        lblicon9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 229, 229));
        setMinimumSize(new java.awt.Dimension(635, 530));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pa.setBackground(new java.awt.Color(51, 51, 51));
        pa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paMouseDragged(evt);
            }
        });
        pa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paMousePressed(evt);
            }
        });
        pa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button3.setBackground(new java.awt.Color(0, 0, 0));
        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Subtract_20px_1.png"))); // NOI18N
        button3.setColorHover(new java.awt.Color(203, 203, 203));
        button3.setColorNormal(new java.awt.Color(0, 0, 0));
        button3.setColorPressed(new java.awt.Color(203, 203, 203));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        pa.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 50, -1));

        button2.setBackground(new java.awt.Color(0, 0, 0));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Delete_20px_1.png"))); // NOI18N
        button2.setColorHover(new java.awt.Color(51, 51, 51));
        button2.setColorNormal(new java.awt.Color(0, 0, 0));
        button2.setColorPressed(new java.awt.Color(255, 255, 255));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        pa.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 40, -1));

        getContentPane().add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        btncalc.setBackground(new java.awt.Color(229, 229, 229));
        btncalc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncalc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btncalcMouseMoved(evt);
            }
        });
        btncalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncalcMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncalcMouseExited(evt);
            }
        });

        lblicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/integral1.png"))); // NOI18N

        lbltxt.setBackground(new java.awt.Color(138, 31, 45));
        lbltxt.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lbltxt.setForeground(new java.awt.Color(138, 31, 45));
        lbltxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltxt.setText("Calcular");

        javax.swing.GroupLayout btncalcLayout = new javax.swing.GroupLayout(btncalc);
        btncalc.setLayout(btncalcLayout);
        btncalcLayout.setHorizontalGroup(
            btncalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btncalcLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        btncalcLayout.setVerticalGroup(
            btncalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btn5.setBackground(new java.awt.Color(229, 229, 229));
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn5MouseMoved(evt);
            }
        });
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5MouseExited(evt);
            }
        });

        lbltxt9.setBackground(new java.awt.Color(138, 31, 45));
        lbltxt9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lbltxt9.setForeground(new java.awt.Color(138, 31, 45));
        lbltxt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltxt9.setText("Acerca de");

        lblicon9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblicon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Info_80px_1.png"))); // NOI18N

        javax.swing.GroupLayout btn5Layout = new javax.swing.GroupLayout(btn5);
        btn5.setLayout(btn5Layout);
        btn5Layout.setHorizontalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn5Layout.createSequentialGroup()
                        .addComponent(lblicon9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btn5Layout.createSequentialGroup()
                        .addComponent(lbltxt9, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        btn5Layout.setVerticalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblicon9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbltxt9)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btncalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 635, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseMoved
        // TODO add your handling code here:
        btn5.setBackground(new Color (48,48,48));
    }//GEN-LAST:event_btn5MouseMoved

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        acercd c = new acercd();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn5MouseClicked

    private void btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseExited
        // TODO add your handling code here:
        btn5.setBackground(new Color (229,229,229));
    }//GEN-LAST:event_btn5MouseExited

    private void btncalcMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalcMouseMoved
        // TODO add your handling code here:
        btncalc.setBackground(new Color (48,48,48));
        //btn.setBackground(new Color (213,29,55));
        //lbltxt.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_btncalcMouseMoved

    private void btncalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalcMouseClicked
        // TODO add your handling code here:
        graficar open = new graficar();
        open.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncalcMouseClicked

    private void btncalcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalcMouseExited
        // TODO add your handling code here:
        btncalc.setBackground(new Color (229,229,229));
        //btn.setBackground(new Color (229,229,229));
     
    }//GEN-LAST:event_btncalcMouseExited

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        this.setState(ventanaPrcp.ICONIFIED);
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_button2ActionPerformed

    private void paMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paMousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_paMousePressed

    private void paMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paMouseDragged
        int xx = evt.getXOnScreen();
        int xy = evt.getYOnScreen();
        
       this.setLocation(xx-x,xy-y);
    }//GEN-LAST:event_paMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrcp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn5;
    public static javax.swing.JPanel btncalc;
    private boton.button button2;
    private boton.button button3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblicon9;
    public static javax.swing.JLabel lbltxt;
    private javax.swing.JLabel lbltxt9;
    private javax.swing.JPanel pa;
    // End of variables declaration//GEN-END:variables
}
